"""Regenerate bourse/symbols.py from Wikipedia's S&P 500 list.

Run occasionally; the index changes a few times a year.

    uv run python scripts/update_symbols.py
"""

import re
import urllib.request
from html.parser import HTMLParser
from pathlib import Path

URL = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"


class Constituents(HTMLParser):
    """Pull the first table on the page: ticker in column 0, name in column 1."""

    def __init__(self):
        super().__init__()
        self.in_table = self.in_row = self.in_cell = False
        self.done = False
        self.row: list[str] = []
        self.cell = ""
        self.rows: list[list[str]] = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag == "table" and not self.done and "wikitable" in (attrs.get("class") or ""):
            self.in_table = True
        elif self.in_table and tag == "tr":
            self.in_row, self.row = True, []
        elif self.in_row and tag in ("td", "th"):
            self.in_cell, self.cell = True, ""

    def handle_endtag(self, tag):
        if tag == "table" and self.in_table:
            self.in_table, self.done = False, True
        elif tag == "tr" and self.in_row:
            self.in_row = False
            if len(self.row) >= 2:
                self.rows.append(self.row)
        elif tag in ("td", "th") and self.in_cell:
            self.in_cell = False
            self.row.append(re.sub(r"\s+", " ", self.cell).strip())

    def handle_data(self, data):
        if self.in_cell:
            self.cell += data


def main() -> None:
    request = urllib.request.Request(URL, headers={"User-Agent": "Mozilla/5.0"})
    html = urllib.request.urlopen(request, timeout=30).read().decode("utf-8")

    parser = Constituents()
    parser.feed(html)

    companies = {}
    for row in parser.rows:
        symbol, name = row[0], row[1]
        if re.fullmatch(r"[A-Z][A-Z.\-]{0,6}", symbol):
            companies[symbol.replace(".", "-")] = name  # BRK.B is BRK-B to Yahoo

    if len(companies) < 400:
        raise SystemExit(f"Only found {len(companies)} companies; the page layout probably moved.")

    lines = [
        '"""The S&P 500, as a plain dict. Generated by scripts/update_symbols.py."""',
        "",
        "SP500 = {",
    ]
    lines += [f'    "{s}": "{n}",' for s, n in sorted(companies.items())]
    lines += ["}", ""]

    target = Path(__file__).resolve().parent.parent / "bourse" / "symbols.py"
    target.write_text("\n".join(lines))
    print(f"Wrote {len(companies)} companies to {target}")


if __name__ == "__main__":
    main()
